image: python:3.6.10-slim-buster


before_script:
  - pip3 install pipenv
  - pipenv install --dev


stages:
  - test


tests:
  stage: test
  script:
    - pipenv run coverage run -m unittest discover
    - pipenv run coverage report -m
    - pipenv run coverage html
    - pipenv run coverage xml
  artifacts:
    paths:
      - htmlcov/*
      - coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.{1,}?((?:[0-9]*[.])?[0-9]+)\%/'
