image: python:3.6.10-slim-buster


before_script:
  - pip3 install pipenv
  - pipenv install --dev


stages:
  - build
  - lint
  - test
  - publish


docs:
  stage: build
  script:
    - pipenv run sphinx-build -d docs/_build/doctrees/ docs/ docs/_build/html/
    - pipenv run sphinx-build -b coverage docs/ docs/_build/coverage/
  artifacts:
    expire_in: 1 week
    paths:
      - docs/_build/html/
      - docs/_build/coverage/python.txt
  only:
    - master
  allow_failure: true


flake8:
  stage: lint
  script:
    - pipenv run flake8 .


version:
  stage: lint
  script:
    - NARRENSCHIFF_VERSION=$( python -c "import narrenschiff; print(narrenschiff.__version__)" )
    - test "${CI_COMMIT_TAG}" == "${NARRENSCHIFF_VERSION}"
  only:
    - tags


tests:
  stage: test
  script:
    - pipenv run coverage run -m unittest discover
    - pipenv run coverage report -m
    - pipenv run coverage html
    - pipenv run coverage xml
  artifacts:
    paths:
      - htmlcov/*
      - coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.{1,}?((?:[0-9]*[.])?[0-9]+)\%/'


stable:
  stage: publish
  script:
    - pip3 install twine
    - echo ${PYPIRC} | base64 -d > "${HOME}/.pypirc"
    - pipenv run python setup.py sdist
    - twine upload dist/narrenschiff-"${CI_COMMIT_TAG}".tar.gz --verbose --repository "${PYPI_REPOSITORY}"
  only:
    - tags
