before_script:
  - apk add --no-cache --update python3
  - apk add --no-cache --update gcc python3-dev musl-dev openssl-dev
  - apk add --no-cache --update libffi libffi-dev
  - pip3 install pipenv
  - pipenv install --dev


stages:
  - lint
  - test
  - publish


stable:
  stage: publish
  image: alpine:3.9.2
  script:
    - python3 -m pip install twine
    - echo ${PYPIRC} | base64 -d > "${HOME}/.pypirc"
    - pipenv run python setup.py sdist
    - twine upload dist/narrenschiff-"${CI_COMMIT_TAG}".tar.gz --verbose --repository "${PYPI_REPOSITORY}"
  only:
    - tags
