image: python:3.6.10-slim-buster


before_script:
  - pip3 install pipenv
  - pipenv install --dev


stages:
  - lint
  - test
  - publish


flake8:
  stage: lint
  script:
    - pipenv run flake8 .


tests:
  stage: test
  script:
    - pipenv run coverage run -m unittest discover
    - pipenv run coverage report -m
    - pipenv run coverage html
    - pipenv run coverage xml
  artifacts:
    paths:
      - htmlcov/*
      - coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.{1,}?((?:[0-9]*[.])?[0-9]+)\%/'


stable:
  stage: publish
  script:
    - pip3 install twine
    - echo ${PYPIRC} | base64 -d > "${HOME}/.pypirc"
    - pipenv run python setup.py sdist
    - twine upload dist/narrenschiff-"${CI_COMMIT_TAG}".tar.gz --verbose --repository "${PYPI_REPOSITORY}"
  only:
    - tags
