image: python:3.6.10-slim-buster


before_script:
  - pip3 install pipenv
  - pipenv install --dev


stages:
  - lint
  - test


version:
  stage: lint
  script:
    - NARRENSCHIFF_VERSION=$( python -c "import narrenschiff; print(narrenschiff.__version__)" )
    - test "${CI_COMMIT_TAG}" == "${NARRENSCHIFF_VERSION}"
  only:
    - tags


tests:
  stage: test
  script:
    - pipenv run coverage run -m unittest discover
    - pipenv run coverage report -m
    - pipenv run coverage html
    - pipenv run coverage xml
  artifacts:
    paths:
      - htmlcov/*
      - coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.{1,}?((?:[0-9]*[.])?[0-9]+)\%/'
