---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      # Use rtrim when next tag has identation
{{ nginx.labels | indent(width=6, indentfirst=True) | rtrim }}
  replicas: {{ nginx.replicas }}
  template:
    metadata:
      labels:
{{ nginx.labels | indent(width=8, indentfirst=True) | rtrim }}
    spec:
      containers:
      - name: nginx
        image: {{ nginx.image }}:{{ nginx.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: log
          emptyDir: {}
