name: Code Quality

on: ["push"]

jobs:

  flake8:
    name: Lint code with flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.6
      - name: Install flake8
        run: pip install flake8
      - name: Lint
        run: flake8 .

  pylint:
    name: Lint code with pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.6
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint and generate report
        run: 'pylint --exit-zero -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" **/*.py | tee pylint.txt'

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.6
      - name: Install pipenv
        run: pip install pipenv
      - name: Install project dependencies
        run: pipenv install --dev
      - name: Run unit tests
        run: pipenv run coverage run -m unittest discover
      - name: Generate coverage reports
        run: |
          pipenv run coverage report -m
          pipenv run coverage html
          pipenv run coverage xml
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pipenv run coveralls --service=github
